//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetASPnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratTravailSoumis
    {
        public ContratTravailSoumis()
        {
            this.Examen = new HashSet<Examen>();
            this.Risque = new HashSet<Risque>();
        }
    
        public decimal contrat_id { get; set; }
        public System.DateTime dateDebut { get; set; }
        public decimal numero { get; set; }
        public decimal personne_id { get; set; }
        public System.DateTime dateFin { get; set; }
    
        public virtual Entreprise Entreprise { get; set; }
        public virtual Travailleur Travailleur { get; set; }
        public virtual ICollection<Examen> Examen { get; set; }
        public virtual ICollection<Risque> Risque { get; set; }
    }
}
