//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetASPnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise
    {
        public Entreprise()
        {
            this.ContratTravailSoumis = new HashSet<ContratTravailSoumis>();
        }
    
        public decimal numero { get; set; }
        public string denomation { get; set; }
        public string adresse { get; set; }
        public string numeroTel { get; set; }
        public decimal nbTravailleurSoumis { get; set; }
        public decimal nbTravailleurNonSoumis { get; set; }
    
        public virtual ICollection<ContratTravailSoumis> ContratTravailSoumis { get; set; }
    }
}
