//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetASPnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen
    {
        public Examen()
        {
            this.ContratTravailSoumis = new HashSet<ContratTravailSoumis>();
            this.Risque = new HashSet<Risque>();
        }
    
        public decimal code { get; set; }
        public string libelle { get; set; }
        public Nullable<float> prix { get; set; }
        public bool isSelected { get; set; }

        public virtual ICollection<ContratTravailSoumis> ContratTravailSoumis { get; set; }
        public virtual ICollection<Risque> Risque { get; set; }
    }
}
