//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetASPnet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeditRisquesEntities : DbContext
    {
        public MeditRisquesEntities()
            : base("name=MeditRisquesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContratTravailSoumis> ContratTravailSoumis { get; set; }
        public virtual DbSet<Entreprise> Entreprise { get; set; }
        public virtual DbSet<Examen> Examen { get; set; }
        public virtual DbSet<Profession> Profession { get; set; }
        public virtual DbSet<Risque> Risque { get; set; }
        public virtual DbSet<Travailleur> Travailleur { get; set; }
    }
}
