//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetASPnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profession
    {
        public Profession()
        {
            this.Travailleur = new HashSet<Travailleur>();
        }
    
        public decimal code { get; set; }
        public string denomination { get; set; }
    
        public virtual ICollection<Travailleur> Travailleur { get; set; }
    }
}
