//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetASPnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risque
    {
        public Risque()
        {
            this.ContratTravailSoumis = new HashSet<ContratTravailSoumis>();
            this.Examen = new HashSet<Examen>();
        }
    
        public decimal code { get; set; }
        public string libelle { get; set; }
        public bool isSelected { get; set; }
    
        public virtual ICollection<ContratTravailSoumis> ContratTravailSoumis { get; set; }
        public virtual ICollection<Examen> Examen { get; set; }
    }
}
