//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetASPnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travailleur
    {
        public Travailleur()
        {
            this.ContratTravailSoumis = new HashSet<ContratTravailSoumis>();
        }
    
        public decimal personne_id { get; set; }
        public string nom { get; set; }
        public string adresse { get; set; }
        public decimal numeroDossier { get; set; }
        public decimal code { get; set; }
    
        public virtual ICollection<ContratTravailSoumis> ContratTravailSoumis { get; set; }
        public virtual Profession Profession { get; set; }
    }
}
